export enum AppRoutes {
  HOME = 'Home',
  LOGIN = 'Login',
  USER = 'Perfil',
  STORE = 'Créditos',
  VEHICLES = 'Veículos',
  REGISTER = 'Registrar',
  OUT_STORE = 'OutStore',
  TAB_ROUTER = 'TabRouter',
  STACK_ROUTER = 'StackRouter',
  FISCAL = 'Fiscal',
  USERS_ADMINISTRATION = 'Usuários',
  SUCCESS_PIX_SALE = 'PixSucesso',
  SUCCESS_CARD_SALE = 'CreditoSucesso',
}
